### PR TITLE
Check for client availability in a universal way.

### PR DESCRIPTION
**Pull request by rorre**
This makes much cleaner code, however `mypy` doesn't seem to be liking it. It always throws `Item "None" of "Optional[AbstractYippi]" has no attribute "_call_api"` for no reason. Might need to find a way to enforce mypy to think that `self._client` exists.

### CODE REVIEW

**Comment by Deer-Spangle** [comment]
Another option could be to have _client be a generated attribute of _BaseMixin, `@property`, and do the check in there?

**Comment by rorre** [comment]
Hmm, unsure if I understand what you're going for. Can you give sample code?

Here's a few attempts that I've done though:
- Recasting the variable so that it is not `Optional[AbstractYippi]` anymore
```
...
    def wrapper(...):
        self._client = cast(AbstractYippi, self._client)
...
```
- Asserting inside the decorator
```
...
    def wrapper(...):
        assert isinstance(self._client, AbstractYippi)
...
```
None of these seems to have worked.

**Comment by Deer-Spangle** [comment]
My thought was, why have the decorator, why not just:
```
class _BaseMixin:
    def __init__(self, json_data: dict, client: AbstractYippi = None) -> None:
        if json_data:
            self._original_data: dict = deepcopy(json_data)
            self.id: Optional[int] = json_data.get("id")
            self.created_at: Optional[str] = json_data.get("created_at")
            self.updated_at: Optional[str] = json_data.get("updated_at")
        self._base_client = client
    
    @property
    def _client(self) -> AbstractYippi:
        if self._base_client is None:
            raise UserError("Yippi client isn't initialized.")
        return self._base_client
```

Then all the methods that use the client will automatically raise a UserError if the client isn't defined

**Comment by rorre** [comment]
Right, tht does look much simpler, will do in a moment.

**Pull request merged**
